# app/services/quality_gate.py
"""
This service acts as a "quality gate" or "safety check" for answers.

It validates that the answer is good enough before sending it to the user.
If there are problems, it generates a clarifying question instead.

This prevents:
- Empty/useless answers
- Answers with low-quality context
- Situations where we need more information from the user
"""

import re
from typing import List, Optional
from app.schemas.langgraph_state import RetrievalChunk, IntentType


def _has_source_citations(answer: str) -> bool:
    lower = answer.lower()
    return "[legal source" in lower or "[user document" in lower


def _looks_like_explicit_refusal(answer: str) -> bool:
    """
    True only when the model is clearly refusing to answer, not when it discusses
    a missing detail while still giving useful information (false positives).
    """
    text = answer.strip().lower()
    patterns = [
        r"i don'?t have enough information to answer",
        r"i don'?t have enough information in (the )?context",
        r"i cannot answer (this|your) question (based on|with)",
        r"there is no information (in (the )?context|available) to answer",
        r"the (provided )?context does not (contain|include) (any )?information",
    ]
    return any(re.search(p, text) for p in patterns)


def _retrieval_supports_answer(
    legal_chunks: List[RetrievalChunk],
    user_chunks: List[RetrievalChunk],
    intent: IntentType,
) -> bool:
    """
    User-doc and legal retrieval scores are not comparable; averaging them
    falsely flags good legal hits when user chunks score low (or vice versa).
    Use best (and top-k average) per branch instead of a global mean.
    """
    def _top_mean(scores: List[float], k: int = 2) -> float:
        if not scores:
            return 0.0
        top = sorted(scores, reverse=True)[:k]
        return sum(top) / len(top)

    legal_scores = [c.score for c in legal_chunks]
    user_scores = [c.score for c in user_chunks]

    legal_best = max(legal_scores) if legal_scores else 0.0
    user_best = max(user_scores) if user_scores else 0.0
    legal_top_mean = _top_mean(legal_scores)
    user_top_mean = _top_mean(user_scores)

    if intent == IntentType.USER_ONLY:
        return user_best >= 0.22 or user_top_mean >= 0.20
    if intent == IntentType.LEGAL_ONLY:
        return legal_best >= 0.24 or legal_top_mean >= 0.22
    # MIXED: either branch can carry the answer
    legal_ok = legal_best >= 0.24 or legal_top_mean >= 0.22
    user_ok = user_best >= 0.20 or user_top_mean >= 0.18
    return legal_ok or user_ok


def validate_answer(
    draft_answer: str,
    legal_chunks: List[RetrievalChunk],
    user_chunks: List[RetrievalChunk],
    intent: IntentType,
    user_has_docs: bool
) -> tuple[bool, Optional[str]]:
    """
    Validates the answer and determines if we need clarification.
    
    How it works:
    1. Check if the answer is too short or generic
    2. Check if we expected user documents but got none
    3. Check if we expected legal knowledge but got none
    4. If any issues, generate a clarifying question
    
    Args:
        draft_answer: The answer generated by the LLM
        legal_chunks: Retrieved chunks from legal knowledge
        user_chunks: Retrieved chunks from user documents
        intent: What type of question was this (LEGAL_ONLY, USER_ONLY, MIXED)
        user_has_docs: Does the user have uploaded documents?
    
    Returns:
        tuple: (is_valid, clarifying_question)
        - is_valid: True if answer is good, False if we need clarification
        - clarifying_question: The question to ask user (None if is_valid is True)
    
    Examples:
        # Good answer
        validate_answer("You can work 40 hours with Stamp 4...", [...], [...], MIXED, True)
        → (True, None)
        
        # User asked about their docs but has none uploaded
        validate_answer("...", [], [], USER_ONLY, False)
        → (False, "I don't see any uploaded documents. Please upload your document first.")
    """
    
    # ========== CHECK 1: Is the answer too short or empty? ==========
    if not draft_answer or len(draft_answer.strip()) < 20:
        return (
            False,
            "I'm having trouble generating a complete answer. Could you please rephrase your question or provide more details?"
        )
    
    # ========== CHECK 2: Explicit refusal vs. hedging while still answering ==========
    # Broad substring checks ("i'm not sure", "i cannot find") fire when the model
    # answers correctly but mentions a missing detail (e.g. company name) — see quality_gate tests / logs.
    answer_lower = draft_answer.lower()
    cites_sources = _has_source_citations(draft_answer)
    substantive = cites_sources and len(draft_answer.strip()) >= 50

    if _looks_like_explicit_refusal(draft_answer) and not substantive:
        print("[INFO] Answer looks like an explicit refusal (no substantive cited answer)")
        if intent == IntentType.USER_ONLY or intent == IntentType.MIXED:
            if not user_has_docs:
                return (
                    False,
                    "I need to see your documents to answer this question. Please upload your document (IRP, visa letter, etc.) first."
                )
            elif not user_chunks:
                return (
                    False,
                    "I couldn't find relevant information in your uploaded documents. Could you specify which document you're referring to, or provide more details about your question?"
                )
        return (
            False,
            "I need more information to answer your question accurately. Could you please:\n"
            "1. Rephrase your question with more specific details, or\n"
            "2. Let me know what specific aspect you're interested in?"
        )

    # Soft hedge: only if the answer is short and does not cite sources
    if not substantive:
        weak_hedges = [
            "i don't have enough information",
            "not enough context",
        ]
        if any(h in answer_lower for h in weak_hedges):
            print("[INFO] Short answer with weak hedge and no citations - requesting clarification")
            return (
                False,
                "I need more information to answer your question accurately. Could you please:\n"
                "1. Rephrase your question with more specific details, or\n"
                "2. Let me know what specific aspect you're interested in?"
            )
    
    # ========== CHECK 3: Expected user documents but got none ==========
    # For MIXED intent, a substantive cited answer from the legal branch is
    # sufficient on its own. Intent classification often over-labels legal
    # questions as MIXED (e.g. "how do I register MY permission"); we must not
    # discard a good, cited legal answer just because the user's documents had
    # no relevant match (or none were uploaded). USER_ONLY stays strict.
    has_strong_legal_answer = bool(legal_chunks) and substantive
    requires_user_docs = intent == IntentType.USER_ONLY or (
        intent == IntentType.MIXED and not has_strong_legal_answer
    )

    if requires_user_docs:
        if not user_has_docs:
            # User is asking about their docs but hasn't uploaded any
            return (
                False,
                "It looks like you're asking about your personal documents, but I don't see any uploaded documents in your account. "
                "Please upload your document first, then I can help you understand it."
            )

        if not user_chunks:
            # User has docs but we didn't find relevant chunks
            return (
                False,
                "I searched your uploaded documents but couldn't find information relevant to your question. "
                "Could you:\n"
                "1. Specify which document you're referring to, or\n"
                "2. Rephrase your question, or\n"
                "3. Upload the specific document you're asking about?"
            )
    
    # ========== CHECK 4: Expected legal knowledge but got none ==========
    if intent in [IntentType.LEGAL_ONLY, IntentType.MIXED]:
        if not legal_chunks:
            # Couldn't find legal information
            return (
                False,
                "I couldn't find specific information about this in our legal knowledge base. "
                "You might want to:\n"
                "1. Check the official Irish immigration website (www.irishimmigration.ie)\n"
                "2. Rephrase your question with different terms\n"
                "3. Contact the immigration office directly for the most accurate information"
            )
    
    # ========== CHECK 5: Retrieval relevance (per-branch, not pooled average) ==========
    all_chunks = legal_chunks + user_chunks
    if all_chunks and not _retrieval_supports_answer(legal_chunks, user_chunks, intent):
        print("[WARN] Retrieval scores too weak for this intent")
        return (
            False,
            "I found some information, but I'm not very confident it answers your question. "
            "Could you rephrase your question or provide more specific details?"
        )
    
    # ========== ALL CHECKS PASSED ==========
    # The answer looks good!
    print("[INFO] Answer passed quality gate validation")
    return (True, None)


def calculate_confidence_score(
    legal_chunks: List[RetrievalChunk],
    user_chunks: List[RetrievalChunk]
) -> float:
    """
    Helper function: Calculate a confidence score for the answer.
    
    This helps us understand how confident we are in our answer based on:
    - Number of chunks retrieved
    - Relevance scores of those chunks
    
    Returns:
        float: Confidence score from 0.0 to 1.0
        - 0.0-0.3: Low confidence (probably need clarification)
        - 0.3-0.7: Medium confidence (answer is okay)
        - 0.7-1.0: High confidence (answer is probably good)
    """
    all_chunks = legal_chunks + user_chunks
    
    if not all_chunks:
        return 0.0
    
    # Calculate average relevance score
    avg_score = sum(chunk.score for chunk in all_chunks) / len(all_chunks)
    
    # Bonus for having multiple sources
    num_sources = len(all_chunks)
    source_bonus = min(num_sources / 10, 0.2)  # Up to 0.2 bonus for having many sources
    
    # Final confidence (capped at 1.0)
    confidence = min(avg_score + source_bonus, 1.0)
    
    return confidence

