# app/services/quality_gate.py
"""
This service acts as a "quality gate" or "safety check" for answers.

It validates that the answer is good enough before sending it to the user.
If there are problems, it generates a clarifying question instead.

This prevents:
- Empty/useless answers
- Answers with low-quality context
- Situations where we need more information from the user
"""

from typing import List, Optional
from app.schemas.langgraph_state import RetrievalChunk, IntentType


def validate_answer(
    draft_answer: str,
    legal_chunks: List[RetrievalChunk],
    user_chunks: List[RetrievalChunk],
    intent: IntentType,
    user_has_docs: bool
) -> tuple[bool, Optional[str]]:
    """
    Validates the answer and determines if we need clarification.
    
    How it works:
    1. Check if the answer is too short or generic
    2. Check if we expected user documents but got none
    3. Check if we expected legal knowledge but got none
    4. If any issues, generate a clarifying question
    
    Args:
        draft_answer: The answer generated by the LLM
        legal_chunks: Retrieved chunks from legal knowledge
        user_chunks: Retrieved chunks from user documents
        intent: What type of question was this (LEGAL_ONLY, USER_ONLY, MIXED)
        user_has_docs: Does the user have uploaded documents?
    
    Returns:
        tuple: (is_valid, clarifying_question)
        - is_valid: True if answer is good, False if we need clarification
        - clarifying_question: The question to ask user (None if is_valid is True)
    
    Examples:
        # Good answer
        validate_answer("You can work 40 hours with Stamp 4...", [...], [...], MIXED, True)
        → (True, None)
        
        # User asked about their docs but has none uploaded
        validate_answer("...", [], [], USER_ONLY, False)
        → (False, "I don't see any uploaded documents. Please upload your document first.")
    """
    
    # ========== CHECK 1: Is the answer too short or empty? ==========
    if not draft_answer or len(draft_answer.strip()) < 20:
        return (
            False,
            "I'm having trouble generating a complete answer. Could you please rephrase your question or provide more details?"
        )
    
    # ========== CHECK 2: Does the answer indicate missing information? ==========
    # Look for phrases that suggest the LLM couldn't answer properly
    uncertain_phrases = [
        "i don't have enough information",
        "i cannot find",
        "not enough context",
        "i'm not sure",
        "i don't see any information"
    ]
    
    answer_lower = draft_answer.lower()
    if any(phrase in answer_lower for phrase in uncertain_phrases):
        # The LLM admitted it doesn't know - we need more info
        print("[INFO] Answer contains uncertainty phrases - requesting clarification")
        
        # Generate a helpful clarifying question based on intent
        if intent == IntentType.USER_ONLY or intent == IntentType.MIXED:
            if not user_has_docs:
                return (
                    False,
                    "I need to see your documents to answer this question. Please upload your document (IRP, visa letter, etc.) first."
                )
            elif not user_chunks:
                return (
                    False,
                    "I couldn't find relevant information in your uploaded documents. Could you specify which document you're referring to, or provide more details about your question?"
                )
        
        # Generic clarification for other cases
        return (
            False,
            "I need more information to answer your question accurately. Could you please:\n"
            "1. Rephrase your question with more specific details, or\n"
            "2. Let me know what specific aspect you're interested in?"
        )
    
    # ========== CHECK 3: Expected user documents but got none ==========
    if intent in [IntentType.USER_ONLY, IntentType.MIXED]:
        if not user_has_docs:
            # User is asking about their docs but hasn't uploaded any
            return (
                False,
                "It looks like you're asking about your personal documents, but I don't see any uploaded documents in your account. "
                "Please upload your document first, then I can help you understand it."
            )
        
        if user_has_docs and not user_chunks:
            # User has docs but we didn't find relevant chunks
            return (
                False,
                "I searched your uploaded documents but couldn't find information relevant to your question. "
                "Could you:\n"
                "1. Specify which document you're referring to, or\n"
                "2. Rephrase your question, or\n"
                "3. Upload the specific document you're asking about?"
            )
    
    # ========== CHECK 4: Expected legal knowledge but got none ==========
    if intent in [IntentType.LEGAL_ONLY, IntentType.MIXED]:
        if not legal_chunks:
            # Couldn't find legal information
            return (
                False,
                "I couldn't find specific information about this in our legal knowledge base. "
                "You might want to:\n"
                "1. Check the official Irish immigration website (www.irishimmigration.ie)\n"
                "2. Rephrase your question with different terms\n"
                "3. Contact the immigration office directly for the most accurate information"
            )
    
    # ========== CHECK 5: Very low quality chunks (low relevance scores) ==========
    all_chunks = legal_chunks + user_chunks
    if all_chunks:
        # Check if all chunks have very low scores (< 0.3 is usually not very relevant)
        avg_score = sum(chunk.score for chunk in all_chunks) / len(all_chunks)
        if avg_score < 0.3:
            print(f"[WARN] Low average relevance score: {avg_score}")
            return (
                False,
                "I found some information, but I'm not very confident it answers your question. "
                "Could you rephrase your question or provide more specific details?"
            )
    
    # ========== ALL CHECKS PASSED ==========
    # The answer looks good!
    print("[INFO] Answer passed quality gate validation")
    return (True, None)


def calculate_confidence_score(
    legal_chunks: List[RetrievalChunk],
    user_chunks: List[RetrievalChunk]
) -> float:
    """
    Helper function: Calculate a confidence score for the answer.
    
    This helps us understand how confident we are in our answer based on:
    - Number of chunks retrieved
    - Relevance scores of those chunks
    
    Returns:
        float: Confidence score from 0.0 to 1.0
        - 0.0-0.3: Low confidence (probably need clarification)
        - 0.3-0.7: Medium confidence (answer is okay)
        - 0.7-1.0: High confidence (answer is probably good)
    """
    all_chunks = legal_chunks + user_chunks
    
    if not all_chunks:
        return 0.0
    
    # Calculate average relevance score
    avg_score = sum(chunk.score for chunk in all_chunks) / len(all_chunks)
    
    # Bonus for having multiple sources
    num_sources = len(all_chunks)
    source_bonus = min(num_sources / 10, 0.2)  # Up to 0.2 bonus for having many sources
    
    # Final confidence (capped at 1.0)
    confidence = min(avg_score + source_bonus, 1.0)
    
    return confidence

