version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: shaastra_postgres
    environment:
      POSTGRES_USER: shaastra
      POSTGRES_PASSWORD: shaastra_password
      POSTGRES_DB: shaastra_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
